### ISSUE TITLE
update tidy_add_coefficients_type() for binomial model with log link

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#101]
@ddsjoberg 

Following https://github.com/ddsjoberg/gtsummary/issues/788 we could consider to update `tidy_add_coefficients_type()` to take into account binomial models with log link.

Such models produce Relative Risks (RR) or Prevalence Ratios (PR) estimates. 

A possibility would be to have a new coefficient type "prevalence_ratio" (with the associated coefficient_label "PR" or "log(PR)"?

Or would you prefer "relative_risk" / "RR" or "log(RR)"

Would it be problematic on `gtsummary` side? maybe just a litte update to deal with acronym def?

**Comment by ddsjoberg** [comment]
Adding the acronym would be great. I prefer relative risk as the default I'd you're ok with that!

**Comment by larmarange** [comment]
@ddsjoberg It works OK  with gtsummary. Just no acronym definition in footnote (that part is managed by gtsummary directly)

``` r
library(broom.helpers)
library(gtsummary)
#> 
#> Attachement du package : 'gtsummary'
#> The following objects are masked from 'package:broom.helpers':
#> 
#>     all_continuous, all_contrasts
mod <- glm(response ~ age + grade * trt, gtsummary::trial, family = binomial(log))
mod %>% tbl_regression(exponentiate = TRUE) 
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
```

![image](https://user-images.githubusercontent.com/966307/108368010-477bf200-71fa-11eb-8686-d5c977abad06.png)


<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
