### ISSUE TITLE
try parameters if tiyd_fun fail?

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#104]
- add a `tidy_parameters()` custom tieders using parameters instead of broom
- in `tidy_and_attach()`, if `tidy_fun` fails, try `tidy_parameters` and show a message

**Comment by larmarange** [comment]
@ddsjoberg I have added a `tidy_parameters()` custom tidier based on `parameters::model_parameters()` in #111  because some models are not supported by `tidy()`.

Regarding `tidy_and_attach()`, for simplifying the use for most users, I was thinking that for most users it would be good to tryCatch `tidy()` and, if not successful, to use `tidy_parameters()`.

I see two possibilities:

- create a `tidy_with_broom_or_paramaters()` tidier implementing this `tryCatch` and defining this tidier as default value for `tidy_fun`
- or updating `tidy_and_attach()` to try `tidy_fun` first and then try `tidy_paramters()`. However, I have the feeling that it is less explicit and when someone pass a custom tieder we should not go back on `tidy_parameters()` in case of failure.

What do you think?

**Comment by larmarange** [comment]
@ddsjoberg I have drafted `tidy_with_broom_or_parameters()`

For now, in all cases, it returns a message explaining which tieder was used. Should I add a `quiet` option or a message explaining to provide an explicit tidier to turn the message off?

For `tidy_plus_plus()`, instead of using `NULL` as default, I simply changed the default to `tidy_with_broom_or_parameters()`. I have the feeling that it would be more explicit and visible.

What do you think?

**Comment by ddsjoberg** [comment]
> For now, in all cases, it returns a message explaining which tieder was used. Should I add a quiet option or a message explaining to provide an explicit tidier to turn the message off?

hmm, good question. I would suggest one of two ways forward. 1. No messaging when `broom::tidy()` works. But when it fails and parameters succeeds add this message, `"The `broom::tidy(x)` errored, and `parameters::model_parameters()` was used instead. Add `tidy_fun = parameters::model_parameters` to quiet this message."` (I think the code passed in tidy_fun would have the extra step/argument to make it tidy format). Or, 2. Add a quiet argument.  I would probably set this to always be quiet though to avoid the messaging when broom::tidy is used, which is the vast majority of the time. I do like letting users know what is being used to tidy their model results, and i think it's needed.

> For tidy_plus_plus(), instead of using NULL as default, I simply changed the default to tidy_with_broom_or_parameters(). I have the feeling that it would be more explicit and visible.

That sounds good to me.  Will you also export that function, so I can use it in gtsummary?

**Comment by larmarange** [comment]
Yes the function will be exported.

I will update the messages.

**Comment by larmarange** [comment]
now fixed
