### ISSUE TITLE
Error in nnet

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#109]
Hey hey, 

This issue was reported today for a multinomial model. I didn't get a chance to look into the details yet, but wanted to record it here.

``` r
library(nnet)
library(MASS)
library(magrittr)

test1 <- multinom(race ~ age + lwt + bwt, data = birthwt)
#> # weights:  15 (8 variable)
#> initial  value 207.637723 
#> iter  10 value 168.608572
#> final  value 168.587348 
#> converged

broom::tidy(test1) %>% knitr::kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">y.level</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.0502611</td>
<td style="text-align: right;">0.0009135</td>
<td style="text-align: right;">2244.476995</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.1464569</td>
<td style="text-align: right;">0.0394259</td>
<td style="text-align: right;">-3.714736</td>
<td style="text-align: right;">0.0002034</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">lwt</td>
<td style="text-align: right;">0.0205184</td>
<td style="text-align: right;">0.0068180</td>
<td style="text-align: right;">3.009432</td>
<td style="text-align: right;">0.0026174</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">bwt</td>
<td style="text-align: right;">-0.0009939</td>
<td style="text-align: right;">0.0002851</td>
<td style="text-align: right;">-3.485562</td>
<td style="text-align: right;">0.0004911</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.9546842</td>
<td style="text-align: right;">0.0004048</td>
<td style="text-align: right;">9769.456437</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.0553396</td>
<td style="text-align: right;">0.0285068</td>
<td style="text-align: right;">-1.941279</td>
<td style="text-align: right;">0.0522245</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">lwt</td>
<td style="text-align: right;">-0.0129022</td>
<td style="text-align: right;">0.0059785</td>
<td style="text-align: right;">-2.158092</td>
<td style="text-align: right;">0.0309207</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">bwt</td>
<td style="text-align: right;">-0.0004768</td>
<td style="text-align: right;">0.0002111</td>
<td style="text-align: right;">-2.258674</td>
<td style="text-align: right;">0.0239037</td>
</tr>
</tbody>
</table>

``` r
broom.helpers::tidy_plus_plus(test1)
#> Error: Join columns must be present in data.
#> x Problem with `term`.
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by larmarange** [comment]
Thanks for the feedback. It seems related to add_n feature.

``` r
library(nnet)
library(MASS)
library(broom.helpers)

test1 <- multinom(race ~ age + lwt + bwt, data = birthwt)
#> # weights:  15 (8 variable)
#> initial  value 207.637723 
#> iter  10 value 168.608572
#> final  value 168.587348 
#> converged
test1 %>% tidy_plus_plus()
#> Error: Join columns must be present in data.
#> x Problem with `term`.
test1 %>% tidy_plus_plus(add_n = FALSE)
#> # A tibble: 6 x 17
#>   y.level term  variable var_label var_class var_type var_nlevels contrasts
#>   <chr>   <chr> <chr>    <chr>     <chr>     <chr>          <int> <chr>    
#> 1 2       age   age      age       integer   continu~          NA <NA>     
#> 2 2       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 3 2       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> 4 3       age   age      age       integer   continu~          NA <NA>     
#> 5 3       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 6 3       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> # ... with 9 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>, conf.low <dbl>, conf.high <dbl>
test1 %>% tidy_and_attach() %>% tidy_add_n()
#> Error: Join columns must be present in data.
#> x Problem with `term`.
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by larmarange** [comment]
OK the problem comes from the fact that race is not coded as a factor. Easy solution: transform race before computing the model

``` r
library(nnet)
library(MASS)
library(broom.helpers)

tmp <- birthwt
tmp$race <- factor(tmp$race)
test2 <- multinom(race ~ age + lwt + bwt, data = tmp)
#> # weights:  15 (8 variable)
#> initial  value 207.637723 
#> iter  10 value 168.608572
#> final  value 168.587348 
#> converged
test2 %>% tidy_plus_plus()
#> # A tibble: 6 x 19
#>   y.level term  variable var_label var_class var_type var_nlevels contrasts
#>   <chr>   <chr> <chr>    <chr>     <chr>     <chr>          <int> <chr>    
#> 1 2       age   age      age       integer   continu~          NA <NA>     
#> 2 2       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 3 2       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> 4 3       age   age      age       integer   continu~          NA <NA>     
#> 5 3       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 6 3       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> # ... with 11 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, n_obs <dbl>, n_event <dbl>, estimate <dbl>, std.error <dbl>,
#> #   statistic <dbl>, p.value <dbl>, conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by larmarange** [comment]
Should be fixed now

``` r
library(nnet)
library(MASS)
library(broom.helpers)

test1 <- multinom(race ~ age + lwt + bwt, data = birthwt)
#> # weights:  15 (8 variable)
#> initial  value 207.637723 
#> iter  10 value 168.608572
#> final  value 168.587348 
#> converged
test1 %>% tidy_plus_plus()
#> # A tibble: 6 x 19
#>   y.level term  variable var_label var_class var_type var_nlevels contrasts
#>   <chr>   <chr> <chr>    <chr>     <chr>     <chr>          <int> <chr>    
#> 1 2       age   age      age       integer   continu~          NA <NA>     
#> 2 2       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 3 2       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> 4 3       age   age      age       integer   continu~          NA <NA>     
#> 5 3       lwt   lwt      lwt       integer   continu~          NA <NA>     
#> 6 3       bwt   bwt      bwt       integer   continu~          NA <NA>     
#> # ... with 11 more variables: contrasts_type <chr>, reference_row <lgl>,
#> #   label <chr>, n_obs <dbl>, n_event <dbl>, estimate <dbl>, std.error <dbl>,
#> #   statistic <dbl>, p.value <dbl>, conf.low <dbl>, conf.high <dbl>
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
Wowow, so fast! Thanks
