### ISSUE TITLE
Consistency of args passed

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#11]
This is so minor, but wanted to point it out just in case!

The `tidy_plus_plus()` fn accepts the arg `conf.int=` and also the `...` which are passed to `tidy_fun=`. Is there a reason to include `conf.int=` here, but not in `tidy_and_attach()` for example. 

There are other common tidy arguments not included, e.g. `exponentiate=`. To be consistent, should `conf.int=` argument be removed?

**Comment by larmarange** [comment]
I was thinking that for basic users it would be good to have confidence intervals to be computed by default. This is why I added it as en explicit argument. Maybe it could be good to add explicitly exponentiate?

My idea was that tidy_plus_plus could be an easy solution for basic users wanting an improved tidier in one go, and keeping all the other helpers for those in need of fine control.

Maybe it is creating confusion and not a good idea...

**Comment by ddsjoberg** [comment]
I think there are no wrong answers here, and it's not confusing the way it currently is written. That said, I think it would be more clear to either add `exponentiate=`, or remove `conf.int=`
