### ISSUE TITLE
How best to handle tidy methods that do not accept `exponentiate=` argument

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#114]
Hey hey @larmarange !

Not all tidying methods support the `exponentiate=` argument. In the example below, the argument is lost to the `broom::tidy(...)` argument. The coefs are not exponentiated and the users are not warned.

``` r
mod <- MASS::glm.nb(response ~ age, gtsummary::trial) 

broom::tidy(mod)
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)  -1.77     0.479       -3.70 0.000215
#> 2 age           0.0128   0.00925      1.39 0.165
broom::tidy(mod, exponentiate = TRUE)
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)  -1.77     0.479       -3.70 0.000215
#> 2 age           0.0128   0.00925      1.39 0.165
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I thought perhaps we could check that argument names with something like this:
``` r
names(as.list(broom.helpers::tidy_plus_plus))
#>  [1] "model"                          "tidy_fun"                      
#>  [3] "conf.int"                       "exponentiate"                  
#>  [5] "variable_labels"                "term_labels"                   
#>  [7] "interaction_sep"                "categorical_terms_pattern"     
#>  [9] "disambiguate_terms"             "disambiguate_sep"              
#> [11] "add_reference_rows"             "no_reference_row"              
#> [13] "add_estimate_to_reference_rows" "add_header_rows"               
#> [15] "show_single_row"                "add_n"                         
#> [17] "intercept"                      "include"                       
#> [19] "keep_model"                     "quiet"                         
#> [21] "strict"                         "..."                           
#> [23] ""
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

But this code doesn't work for S3 methods.

At one point, I thought I saw a broom GitHub Issue about warning users of arguments lost to the `...`, but I can't find it now.

Here's a post from a confused user
https://stackoverflow.com/questions/67061268/tbl-regression-from-the-gtsummary-package-for-negative-binomial-regressions

Is there anything we could do on our side to inform users when arguments are not used?

**Comment by larmarange** [comment]
Right now, if `exponentiate` is not supported by a tidier (i.e. resulting in a error) we try without that argument and we indicate that this argument is not relevant for such tider. cf. https://github.com/larmarange/broom.helpers/blob/21d87ea51ae9c9b3f29a3a4d5931cd42858e41c0/R/tidiers.R#L72

**Comment by ddsjoberg** [comment]
But that is only tried if passing the `exponentiate=` argument causes an error, right? In this case, the argument is simply ignored by `broom::tidy()`.

**Comment by larmarange** [comment]
Regarding neg binomial, I do not have the same result:

```r
> broom::tidy(mod, exponentiate = TRUE)
# A tibble: 2 x 5
  term        estimate std.error statistic  p.value
  <chr>          <dbl>     <dbl>     <dbl>    <dbl>
1 (Intercept)    0.170   0.479       -3.70 0.000215
2 age            1.01    0.00925      1.39 0.165   
Warning message:
Tidiers for objects of class negbin are not maintained by the broom team, and are only supported through the glm tidier method. Please be cautious in interpreting and reporting broom output. 
```

**Comment by larmarange** [comment]
In `tidy_and_attach()`

- we check so far only for `lm` models because `tidy()` does not produce an error when exponentiating. If `exponentiate = TRUE` a stop with an appropriate message is produced
- then we try `tidy_fun` with the `exponentiate` argument
- if an error is produced, we try again without the exponentiate argument
- if it works without exponentiate and `exponentiate == FALSE` we simply take the result
- if it works without exponentiate and `exponentiate == TRUE` we just warn that the exponentiate argument is not valid and was ignored. **Here: we should probably have a stop instead.**

**Comment by larmarange** [comment]
Regarding, negbin models, I just updated `broom` and it is true.

I would say that in such situation, then a tidier do not handle `exponentiate`, the tieder should return a stop.

Should it be something discussed with `broom` team?

**Comment by larmarange** [comment]
NB: in addition, we cannot assume that `tidy_fun` is always `broom::tidy()`

**Comment by ddsjoberg** [comment]
At minimum, we can add an issue to broom requesting to add the exponentiate arg for negbin. That will work for this case only, however.

I do like the idea of speaking with them about checking for lost `...` arguments. There is an entire package built by Hadley to do just this type of checking https://github.com/r-lib/ellipsis

**Comment by ddsjoberg** [comment]
> NB: in addition, we cannot assume that `tidy_fun` is always `broom::tidy()`

oh right, good point, ugh

**Comment by larmarange** [comment]
> At minimum, we can add an issue to broom requesting to add the exponentiate arg for negbin. That will work for this case only, however.
> 
> I do like the idea of speaking with them about checking for lost `...` arguments. There is an entire package built by Hadley to do just this type of checking https://github.com/r-lib/ellipsis

Both are good ideas. Do you contact them?

**Comment by ddsjoberg** [comment]
yeah i can contact them, I'll add a cc to you as well!

**Comment by ddsjoberg** [comment]
FYI I added the exponentiate argument for negbin models
github.com/tidymodels/broom/pull/1012
