### ISSUE TITLE
Export an `.assert_package()` function?

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#134]
I know you do checks for package installation in broom.helpers, e.g. emmeans. I have a function in gtsummary called `assert_package()` that checks for
1. If the package is installed
2. Also checks whether the package requires a minimum version of a package, e.g. in gtsummary we require the parameters package for some calculations, but we require a more recent version of the package because old versions of the package don't include the functions I used.
3. The function can return either an informative error message OR a boolean indicating whether the pkg (and perhaps the pkg min version) are installed.

Do you think this utility function would be a good fit for broom.helpers? I export it from gtsummary because I also use it in bstfun.

**Comment by ddsjoberg** [comment]
The function's help file

https://www.danieldsjoberg.com/gtsummary/reference/assert_package.html

**Comment by larmarange** [comment]
Hi @ddsjoberg 

Yes it could be useful to move `assert_package()` into `broom.helpers` and to reexport it.

Quick comments:

- to be a little more generic, default for `pkg_search` should be `NULL`
- maybe `gtsummary:::get_min_version_required` could be exported too
- should `gtsummary:::get_min_version_required` look into all dependencies? (currently only in Suggests)

**Comment by ddsjoberg** [comment]
Good comments, I'll submit a PR now, and we can continue the conversation there.
