### ISSUE TITLE
Potential issue with `formula_list_to_named_list(type_check=)`

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#137]
In the `gtsummary::tbl_cross()` we accept a digits argument. But rather than the formula-list notation, we accept a single entry that is applied via `tbl_summary()` as `digits = everything() ~ digits`. When I was updating gtsummary to include the `type_check=` argument, I got an error because `digits=` is most often NULL, and the type check doesn't allow `digits = everything() ~ NULL` because it doesn't pass the check.

It was a simple update to code around this, but to continue to allow all previous syntax to continue working I think we should allow NULL values.

Sounds reasonable to you?

``` r
broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial
)
#> $trt
#> NULL
#> 
#> $age
#> NULL
#> 
#> $marker
#> NULL
#> 
#> $stage
#> NULL
#> 
#> $grade
#> NULL
#> 
#> $response
#> NULL
#> 
#> $death
#> NULL
#> 
#> $ttdeath
#> NULL

broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial,
  type_check = is.character
)
#> Error: Error processing `` argument for element 'trt'. The value passed is not the expected type/class.
```

<sup>Created on 2021-12-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
Dear @ddsjoberg , as always, thank you for your feedback.

I would say that this is expected behaviour. If you want to allow `NULL` if the type checking, you should pass a test allowing `NULL`. It is also more explicit, because you explicitly allow `NULL` in such case.

``` r
broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial,
  type_check = is.null
)
#> $trt
#> NULL
#> 
#> $age
#> NULL
#> 
#> $marker
#> NULL
#> 
#> $stage
#> NULL
#> 
#> $grade
#> NULL
#> 
#> $response
#> NULL
#> 
#> $death
#> NULL
#> 
#> $ttdeath
#> NULL

is_null_or_character <- function(x) {
  is.null(x) | is.character(x)
}

broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial,
  type_check = is_null_or_character
)
#> $trt
#> NULL
#> 
#> $age
#> NULL
#> 
#> $marker
#> NULL
#> 
#> $stage
#> NULL
#> 
#> $grade
#> NULL
#> 
#> $response
#> NULL
#> 
#> $death
#> NULL
#> 
#> $ttdeath
#> NULL
```

<sup>Created on 2021-12-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If I may, in most cases, `gtsummary` functions provide a default value when `NULL` is provided before calling `broom.helpers::.formula_list_to_named_list`. 

I guess that `tbl_cross(digits)` is an exception because it is passed to `tbl_summary()` at some point?

Let me know if I misunderstood one of your points.

**Comment by ddsjoberg** [comment]
You've understood perfectly!

While the `tbl_cross(digits=)` argument is what alerted me to a potential issue, there can be problems for the users too. I would like to avoid is a breaking change for the users.

The `type_check=` argument is meant to identify problematic inputs AND historically we've accepted NULL values. For example, a user could define a list for variable labels that included NULL values, e.g. `list(age = "Age", grade = NULL)` and there would have been no issue. If I add the check `type_check = rlang::is_string`, the syntax will no longer work.

We could update every `type_check=` to allow for a NULL value, `type_check = function(x) rlang::is_string(x) || is.null(x)`. But I feel a simpler solution, consistent with the current allowed syntax, is to allow for NULL values.

**Comment by larmarange** [comment]
OK thank you for the clarification.

Do you think we should add an option `NULL_allowed` (default TRUE) allowing a more strict comparison if needed?

**Comment by larmarange** [comment]
Would #138 be OK for you?
