### ISSUE TITLE
Model Support Request: `plm::plm()` models

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#140]
This stackoverflow post is asking about support for `plm::plm()` models.
https://stackoverflow.com/questions/70560374

I've never used that package/model before. I'll see if I can submit a PR with support for the models tonight.

``` r
library(broom.helpers)
data("Grunfeld", package = "plm")

model <- plm::plm(inv ~ value + capital, data = Grunfeld, model = "within", index = c("firm", "year"))
model
#> 
#> Model Formula: inv ~ value + capital
#> 
#> Coefficients:
#>   value capital 
#> 0.11012 0.31007

broom::tidy(model)
#> # A tibble: 2 x 5
#>   term    estimate std.error statistic  p.value
#>   <chr>      <dbl>     <dbl>     <dbl>    <dbl>
#> 1 value      0.110    0.0119      9.29 3.92e-17
#> 2 capital    0.310    0.0174     17.9  2.22e-42

tidy_plus_plus(model)
#> Error: Tibble columns must have compatible sizes.
#> * Size 2: Existing data.
#> * Size 3: Column `variable`.
#> i Only values of size one are recycled.
```

<sup>Created on 2022-01-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
UPDATE: The issue root is that the `plm()` function does not return an intercept. I was able to add `model_identify_variables.plm()` that fixed the issue with the missing intercept. But I got stuck with a missing reference row. When you get a chance, can you take a look?

**Comment by larmarange** [comment]
I will look at it once back

Joseph Larmarange

Le lun. 3 janv. 2022 à 05:06, Daniel Sjoberg ***@***.***> a
écrit :

**Comment by larmarange** [comment]
OK, I have identified the issue. By default, `plm:::model.matrix.plm()` removes constant columns (i.e. the intercept) resulting in a bug when assigning variable (because the `assign` attribute was not updated accordingly).

```r
model_get_model_matrix.plm <- function(model, ...) {
  stats::model.matrix(model, cstcovar.rm = "none", ...)
}
```

should be enough to fix the bug
