### ISSUE TITLE
Add support for `model_get_n()` for tidycrr model objects

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#143]
I can try to add this support at some time if you're in a busy season :)

```r
remotes::install_github("MSKCC-Epi-Bio/tidycmprsk")
library(tidycmprsk)

crr(Surv(ttdeath, death_cr) ~ age + trt, trial) %>%
  gtsummary::tbl_regression(exponentiate = TRUE) %>%
  add_nevent() # number of events (first competing event)
```

**Comment by larmarange** [comment]
Dear @ddsjoberg 

Can you please check #144 Does it fix the problem? Would you have some other tests to check that results are as expected?

``` r
library(tidycmprsk)
library(broom.helpers)
library(gtsummary)
#> 
#> Attachement du package : 'gtsummary'
#> Les objets suivants sont masqués depuis 'package:broom.helpers':
#> 
#>     all_continuous, all_contrasts
#> L'objet suivant est masqué depuis 'package:tidycmprsk':
#> 
#>     trial

mod <- crr(Surv(ttdeath, death_cr) ~ age + trt, tidycmprsk::trial)
#> 11 cases omitted due to missing values

mod %>% broom.helpers:::model_get_n.coxph()
#> # A tibble: 4 x 4
#>   term        n_obs n_event exposure
#>   <chr>       <dbl>   <dbl>    <dbl>
#> 1 (Intercept)   189     154    3762.
#> 2 age           189     154    3762.
#> 3 trtDrug B      98      83    1888.
#> 4 trtDrug A      91      71    1874.

mod %>%
  tbl_regression(exponentiate = TRUE) %>%
  add_nevent() %>%
  as_kable()
```

| **Characteristic**     | **Event N** | **HR** | **95% CI** | **p-value** |
|:-----------------------|:------------|:-------|:-----------|:------------|
| Age                    | 154         | 1.01   | 0.99, 1.03 | 0.6         |
| Chemotherapy Treatment | 154         |        |            |             |
| Drug A                 |             |        |            |             |
| Drug B                 |             | 1.52   | 0.88, 2.62 | 0.13        |

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
Hmmmm I'm not sure about the results.    For Coxph models, the number of events include all type of events.

If I understand properly `crr()`, you want only the number of events defined by `failure` option? Can you clarify?

**Comment by larmarange** [comment]
I have updated the PR to consider, as the number of events, only status defined by `failcode`. Is it the expected behaviour?

No user-supplied code found … so we’ve made some up. You’re welcome!

``` r
sprintf("Happy %s!", weekdays(Sys.Date()))
#> [1] "Happy mardi!"
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment]
Side question: should we support `tidycuminc` models?

**Comment by ddsjoberg** [comment]
Everything looks flawless! Thank you so much for adding!

**Comment by larmarange** [comment]
Thanks for the feedback. It's merged now.

No worry, I didn't look into the details of tidycuminc. If there is no need, that's OK with me.
