### ISSUE TITLE
Update `.assert_package()`?

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#147]
Should we update to use `rlang::is_installed()` and `rlang::check_installed()` internally? I think it'll improve the user experience when interactive.

- `rlang::is_installed()` doesn't interact with the user. It simply returns TRUE or FALSE depending on whether the packages are installed.

- In interactive sessions, `rlang::check_installed()` asks the user whether to install missing packages. If the user accepts, the packages are installed with pak::pkg_install() if available, or utils::install.packages() otherwise. If the session is non interactive or if the user chooses not to install the packages, the current evaluation is aborted.

**Comment by larmarange** [comment]
Seems good to me. Could you propose a PR?

**Comment by ddsjoberg** [comment]
> Seems good to me. Could you propose a PR?

Will do!

**Comment by ddsjoberg** [comment]
hey hey @larmarange !

I think the issue is pretty strange on R 3.5.  The error is stemming from a call to `reformulate()` in {lme4}, and the error is `unused argument (env = environment(f))`. The `env=` argument wasn't added until 3.6.

You can see in the table below, the function was changed in 3.6 and the env arg was added.

![image](https://user-images.githubusercontent.com/26774684/154300768-3ec43498-9e11-498f-9e17-34cea462839c.png)

I looked in the package's GH repo and they don't use a prefix `stats::reformulate()` when they reference the function (https://github.com/lme4/lme4/search?q=reformulate). So what I think is happening is that the package is installing properly on R 3.5, it's using the old base R of reformulate that doesn't have an env argument.

I think lme4 likely isn't preforming the tests to ensure there are no errors on the older versions of R it claims to support.  What do you think the next best steps are?

**Comment by larmarange** [comment]
I guess we have two options:

- decide that now `broom.helpers` requires 3.6 as a minimum (but I will also impact gtsummary).  Some how, we are now version 4.1
- test R version in examples and test and do not run examples/tests requiring lme4 if R < 3.6

**Comment by ddsjoberg** [comment]
I filed an issue on the lme4 repo https://github.com/lme4/lme4/issues/664 . I vote would to just leave it as is for now with the erroring R Cmd Check. Hopefully lme4 will update either the call to `remformulate(env=)` or update the R versions that are supported, either of which will fix our errors upon the next release.

**Comment by larmarange** [comment]
OK  in that case I propose to merge the PR but to keep this issue open. Is it fine with you?

**Comment by ddsjoberg** [comment]
that sounds good to me! i think they'll update soon enough. i may turn off my 3.5 checks for a while until they do

**Comment by ddsjoberg** [comment]
hey hey @larmarange ! The lme4 package had a new release 11 days ago, and should solve our R CMD Check problems!
https://cran.r-project.org/web/packages/lme4/index.html

**Comment by ddsjoberg** [comment]
FYI, I think I am about 3 to 4 weeks out from a gtsummary release. Is there anything we could add to broom.helpers in the interim? Would you be ok with a broom.helpers release in a few weeks?

**Comment by larmarange** [comment]
> Is there anything we could add to broom.helpers in the interim? 

I do not see anything right now

>Would you be ok with a broom.helpers release in a few weeks?

No problem
