### ISSUE TITLE
Add a vignette

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#15]

**Comment by larmarange** [comment]
fixed by #22

**Comment by ddsjoberg** [comment]
Are there any other vignettes to add before release?  If not, I can remove the drop down list for Articles to a single link to the Getting Started vignette
![image](https://user-images.githubusercontent.com/26774684/91561585-e12cab80-e909-11ea-8d20-1c40f10267c5.png)

**Comment by larmarange** [comment]
No I do not thinks we need an other vignette. I just completed the current with some more advanced examples.

**Comment by larmarange** [comment]
With pleasure for removing the dropdown list (I never explored all options of pkgdown)

**Comment by larmarange** [comment]
Codecoverage is now 100%. We have examples and a vignette.

There may be still some bugs but difficult to identify them without using the package.

What else do you think we should do before a first release?

**Comment by larmarange** [comment]
> Are there any other vignettes to add before release? If not, I can remove the drop down list for Articles to a single link to the Getting Started vignette
> ![image](https://user-images.githubusercontent.com/26774684/91561585-e12cab80-e909-11ea-8d20-1c40f10267c5.png)

done by #27

**Comment by ddsjoberg** [comment]
I don't think there is anything that *needs* to be done...wow!  

There are a couple of things we could think on:
1. I don't think printing the tidy tibble in the README is showing a user what the package can do in the best way.  I am not sure what would be better, however!  Perhaps we add the forest plot to show that it can be created easily?
1. When the header row is added, most columns that are consistent across the variable are filled (e.g. `var_type`, `var_class`, `var_label`).  The `contrasts` column, however, is not filled.  To be consistent, I think it would be a good idea to fill this as well.
1. The columns `reference_row` and `header_row` are logical vectors that are `NA` for some rows.  I think for a new user, it would be easier if these were filled for every row (no `NA`s).
1. One piece of documentation I think would be helpful to include an example tidy tibble with every addition possible along with a detailed description of what each column is (type, function that will add the column, and perhaps an example of how can be used).

**Comment by larmarange** [comment]
> 1. I don't think printing the tidy tibble in the README is showing a user what the package can do in the best way.  I am not sure what would be better, however!  Perhaps we add the forest plot to show that it can be created easily?

This is a good question and it depends on who is the targetted audience of `broom.helpes`: basic users or developers?
I would say that the purpose of this package is mainly to advanced users and programmers.
For basic users:

- the best is to use `tbl_regression()` to print a nice table
- for a forest plot, the easy way will be to use `ggcoef_model()` (https://github.com/larmarange/JLutils/blob/master/R/ggcoef_model.R). Note that this is a dev version in `JLutils`. I intend to rewrite it using `broom.helpers` before integrating it in `GGally`

We can still add a forest plot in README. At a later stage, it would be relevant to update the README to say that the package is used in `gtsummary` (for nice tables) and in `GGally` (for nice model plots).

> 2. When the header row is added, most columns that are consistent across the variable are filled (e.g. `var_type`, `var_class`, `var_label`).  The `contrasts` column, however, is not filled.  To be consistent, I think it would be a good idea to fill this as well.

TRUE. Will update this.

> 3. The columns `reference_row` and `header_row` are logical vectors that are `NA` for some rows.  I think for a new user, it would be easier if these were filled for every row (no `NA`s).

Once again, it depends on the audience.
When I was writing the package, the interest of using `NA` was to indicate an additional piece of information:

- `TRUE` that variable has a reference/header row and this is the reference/header row
- `FALSE` that variable has a reference/header row and this is not the reference/header row
- `NA` that variable **doesn't have** a reference/header row

It is true that it is not explained properly in the documentation.

For future development, I do not know if it is relevant to keep that distinction.

Once again, I'm not sure that basic users will manipulate the output of `tidy_*()` functions.

> 4. One piece of documentation I think would be helpful to include an example tidy tibble with every addition possible along with a detailed description of what each column is (type, function that will add the column, and perhaps an example of how can be used).

Good idea. Through an additional technical vignette?

**Comment by ddsjoberg** [comment]
Thanks for your great responses.  These are just thoughts I wanted to put out there.

1. I like your proposal!  We explain that broom.helpers is the engine behind `tbl_regression()` and the GGally function. Illustrate the broom.helpers fns and show the output from the function that show pretty output. Maybe we just keep it as is for now, and when we've updated the backend of the packages, we can update? If that is ok with you, we can open another issue so we don't forget to make the update later.

2. OK, sounds good

3. I am just pointing this out.  Either option does make sense.  I'll leave it up to you!

4. I'll add a small section to the current vignette now.

**Comment by larmarange** [comment]
> 1. I like your proposal!  We explain that broom.helpers is the engine behind `tbl_regression()` and the GGally function. Illustrate the broom.helpers fns and show the output from the function that show pretty output. Maybe we just keep it as is for now, and when we've updated the backend of the packages, we can update? If that is ok with you, we can open another issue so we don't forget to make the update later.

issue created, cf. #28 

> 2. OK, sounds good

I will look at it this week-end

> 3. I am just pointing this out.  Either option does make sense.  I'll leave it up to you!

OK, for now I will keep like that (more information). It will still be possible to change things later.

But I will update documentation to be clearer

> 4. I'll add a small section to the current vignette now.

Thanks a lot.

I have the feeling that we should be able to release a first version next week.

**Comment by ddsjoberg** [comment]
FYI, I am updating the vignette, and i am getting an error the last code chunk. The error is coming from the `tidy_add_term_labels()` call.

```r
model_4 <- glm(
  response ~ stage + grade * trt,
  gtsummary::trial,
  family = binomial,
  contrasts = list(
    stage = contr.poly,
    grade = contr.helmert,
    trt = contr.poly
  )
)

model_4 %>%
  tidy_and_attach(exponentiate = TRUE) %>%
  tidy_add_reference_rows() %>%
  tidy_add_estimate_to_reference_rows(exponentiate = TRUE) %>%
  tidy_add_term_labels() %>%
  rmarkdown::paged_table()

 Error in if (is.null(names(y)) || any(names(y) == "")) { : 
  missing value where TRUE/FALSE needed 
```

**Comment by larmarange** [comment]
That error should have been fixed today. Did you rebuild the package to be sure to use the last version?

**Comment by larmarange** [comment]
OK 

the 4 elements have been now fixed.  Do you see anything else?

Should we release a first version of CRAN to facilitate integration?

**Comment by ddsjoberg** [comment]
I think it's ready for submission to CRAN! Congratulations!

**Comment by larmarange** [comment]
Thanks for your help
