### ISSUE TITLE
Fix test failure

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#157]
One test is failing:

```r
  expect_equal(
    .get_min_version_required("brms"),
    c(Suggests  = "2.13.0")
  )
```

On my PC this test pass successfully. @ddsjoberg do you have any idea why it is failing on GitHub actions?

**Comment by ddsjoberg** [comment]
Hmmm, I'll look into it more. It's also passing on my machine

**Comment by ddsjoberg** [comment]
Frustrating that this piece of code hasn't been touched in quite some time!

**Comment by larmarange** [comment]
It seems that the package description is not available anymore in the GitHub action context.

A possibility would be to skip the test if `anyNA(utils::packageDescription("broom.helpers"))`

**Comment by larmarange** [comment]
Wrong. It doesn't seem to be the problem.
