### ISSUE TITLE
Warning about missing terms column

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#175]
This warning is being printed when I run the R CMD Checks. We should address this. If it's fine, we can add a `suppressWarning()` or something else?

``` r
library(broom.helpers)

mgcv::gam(response ~ grade, data = gtsummary::trial) |> 
  model_identify_variables()
#> Warning: Unknown or uninitialised column: `term`.
#> Unknown or uninitialised column: `term`.
#> # A tibble: 3 × 5
#>   term        variable var_class var_nlevels var_type   
#>   <chr>       <chr>    <chr>           <int> <chr>      
#> 1 (Intercept) <NA>     <NA>               NA intercept  
#> 2 gradeII     grade    factor              3 categorical
#> 3 gradeIII    grade    factor              3 categorical
```

<sup>Created on 2022-09-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
It seems related with a problem with `broom`.

``` r
library(broom.helpers)

mod <- mgcv::gam(response ~ grade, data = gtsummary::trial)

mod |> 
  broom::tidy()
#> Warning: Unknown or uninitialised column: `term`.
#> Unknown or uninitialised column: `term`.
#> # A tibble: 0 × 1
#> # … with 1 variable: term <chr>
```

<sup>Created on 2022-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
Here, it works with `parametric = TRUE`

``` r
library(broom.helpers)

mod <- mgcv::gam(response ~ grade, data = gtsummary::trial)
mod |> 
  broom::tidy(parametric = TRUE)
#> # A tibble: 3 × 5
#>   term        estimate std.error statistic     p.value
#>   <chr>          <dbl>     <dbl>     <dbl>       <dbl>
#> 1 (Intercept)   0.313     0.0572     5.48  0.000000136
#> 2 gradeII      -0.0118    0.0822    -0.144 0.886      
#> 3 gradeIII      0.0199    0.0822     0.242 0.809

mod |> 
  broom::tidy()
#> Warning: Unknown or uninitialised column: `term`.
#> Unknown or uninitialised column: `term`.
#> # A tibble: 0 × 1
#> # … with 1 variable: term <chr>
```

<sup>Created on 2022-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I am not familiar with GAM models. At this line, https://github.com/larmarange/broom.helpers/blob/570fd0f7099367ebf1503116220304acd09855e4/R/model_identify_variables.R#L167 can we simply use `parametric = TRUE` or should we expect potential side effects?

**Comment by larmarange** [comment]
Another option is to try without parametric = TRUE. If it returns an empty table, retry with parametric = TRUE

**Comment by larmarange** [comment]
Sorry, it took me some time to remember GAM models.

We could just use a `suppressWarning()`. Could I suggest to also add it in `gtsummary::tidy_gam()`?

**Comment by ddsjoberg** [comment]
Thanks @larmarange !
