### ISSUE TITLE
Support for multinomial GEE regression models

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#185]
Today, I stackoverflow user was asking about support for `multgee::nomLORgee()` models. We can keep this open as a record for when we get to it.

```r
library(multgee)
data(housing)   
fitmod <- nomLORgee(y ~ factor(time) * sec, data = housing, id = id, repeated = time)
```

https://stackoverflow.com/questions/73997977

**Comment by larmarange** [comment]
I just had a quick look.

There is no `tidy()` method for such model, but we could use ``tidy_parameters()`.

However, the naming of the coefficient isn't standard. So some work would be required to identify them, or to rename them in a custom tidier.  Also, the `y.level` column is missing from the tidier, and should also be considered.

I will try to see if I can find out something.

**Comment by larmarange** [comment]
Hi,

I have a first draft, by introducing a custom tidier renaming terms according to conventional format and adding a `y.level` column.

Please see #186 

Please not that for proper display in `tbl_regression()` some update is required here https://github.com/ddsjoberg/gtsummary/blob/ea14cbdee7c63cbeade817479c8be2f74fe5e8e2/R/tbl_regression_methods.R#L57

``` r
library(broom.helpers)
library(multgee)
#> Le chargement a nécessité le package : gnm
library(gtsummary)
#> #Uighur
#> 
#> Attachement du package : 'gtsummary'
#> Les objets suivants sont masqués depuis 'package:broom.helpers':
#> 
#>     all_continuous, all_contrasts

housing <- multgee::housing
housing$y2 <- factor(housing$y, labels = c("a", "b", "c"))

mod <- nomLORgee(
  y2 ~ factor(time) * sec, 
  data = housing, 
  id = id,
  repeated = time
)

mod |> 
  tidy_plus_plus() |> 
  dplyr::select(y.level, term, original_term, variable, var_type, reference_row)
#> ℹ multgee model detected.
#> ✔ `tidy_multgee()` used instead.
#> ℹ Add `tidy_fun = broom.helpers::tidy_multgee` to quiet these messages.
#> # A tibble: 16 × 6
#>    y.level term               original_term        variable      var_t…¹ refer…²
#>    <chr>   <chr>              <chr>                <chr>         <chr>   <lgl>  
#>  1 b       factor(time)0      <NA>                 factor(time)  catego… TRUE   
#>  2 b       factor(time)6      factor(time)6:1      factor(time)  catego… FALSE  
#>  3 b       factor(time)12     factor(time)12:1     factor(time)  catego… FALSE  
#>  4 b       factor(time)24     factor(time)24:1     factor(time)  catego… FALSE  
#>  5 b       sec                sec:1                sec           contin… NA     
#>  6 b       factor(time)6:sec  factor(time)6:sec:1  factor(time)… intera… NA     
#>  7 b       factor(time)12:sec factor(time)12:sec:1 factor(time)… intera… NA     
#>  8 b       factor(time)24:sec factor(time)24:sec:1 factor(time)… intera… NA     
#>  9 c       factor(time)0      <NA>                 factor(time)  catego… TRUE   
#> 10 c       factor(time)6      factor(time)6:2      factor(time)  catego… FALSE  
#> 11 c       factor(time)12     factor(time)12:2     factor(time)  catego… FALSE  
#> 12 c       factor(time)24     factor(time)24:2     factor(time)  catego… FALSE  
#> 13 c       sec                sec:2                sec           contin… NA     
#> 14 c       factor(time)6:sec  factor(time)6:sec:2  factor(time)… intera… NA     
#> 15 c       factor(time)12:sec factor(time)12:sec:2 factor(time)… intera… NA     
#> 16 c       factor(time)24:sec factor(time)24:sec:2 factor(time)… intera… NA     
#> # … with abbreviated variable names ¹​var_type, ²​reference_row

# adaptation required in tbl_regression()
# cf. https://github.com/ddsjoberg/gtsummary/blob/ea14cbdee7c63cbeade817479c8be2f74fe5e8e2/R/tbl_regression_methods.R#L57
mod |> 
  tbl_regression(exponentiate = TRUE) |> 
  as_kable()
#> ℹ multgee model detected.
#> ✔ `tidy_multgee()` used instead.
#> ℹ Add `tidy_fun = broom.helpers::tidy_multgee` to quiet these messages.
```

| **Characteristic**  | **exp(Beta)** | **95% CI** | **p-value** |
|:--------------------|:-------------:|:----------:|:-----------:|
| factor(time)        |               |            |             |
| 0                   |       —       |     —      |             |
| 6                   |     0.15      | 0.08, 0.29 |   \<0.001   |
| 12                  |     0.05      | 0.03, 0.11 |   \<0.001   |
| 24                  |     0.06      | 0.03, 0.12 |   \<0.001   |
| sec                 |     0.58      | 0.30, 1.13 |    0.11     |
| factor(time) \* sec |               |            |             |
| 6 \* sec            |     0.31      | 0.12, 0.76 |    0.010    |
| 12 \* sec           |     1.08      | 0.42, 2.79 |     0.9     |
| 24 \* sec           |     1.03      | 0.41, 2.57 |    \>0.9    |
| factor(time)        |               |            |             |
| 0                   |       —       |     —      |             |
| 6                   |     0.78      | 0.43, 1.40 |     0.4     |
| 12                  |     0.57      | 0.31, 1.04 |    0.067    |
| 24                  |     0.35      | 0.19, 0.64 |   \<0.001   |
| sec                 |     0.90      | 0.45, 1.78 |     0.8     |
| factor(time) \* sec |               |            |             |
| 6 \* sec            |     0.20      | 0.09, 0.44 |   \<0.001   |
| 12 \* sec           |     0.13      | 0.05, 0.31 |   \<0.001   |
| 24 \* sec           |     0.35      | 0.15, 0.79 |    0.012    |

``` r

mod2 <- ordLORgee(
  formula = y ~ factor(time) + factor(trt) + factor(baseline),
  data = multgee::arthritis, 
  id = id, 
  repeated = time, 
  LORstr = "uniform"
)

mod2 |> 
  tidy_plus_plus() |> 
  dplyr::select(term, original_term, variable, var_type, reference_row)
#> ℹ multgee model detected.
#> ✔ `tidy_multgee()` used instead.
#> ℹ Add `tidy_fun = broom.helpers::tidy_multgee` to quiet these messages.
#> # A tibble: 10 × 5
#>    term              original_term     variable         var_type    reference_…¹
#>    <chr>             <chr>             <chr>            <chr>       <lgl>       
#>  1 factor(time)1     <NA>              factor(time)     categorical TRUE        
#>  2 factor(time)3     factor(time)3     factor(time)     categorical FALSE       
#>  3 factor(time)5     factor(time)5     factor(time)     categorical FALSE       
#>  4 factor(trt)1      <NA>              factor(trt)      dichotomous TRUE        
#>  5 factor(trt)2      factor(trt)2      factor(trt)      dichotomous FALSE       
#>  6 factor(baseline)1 <NA>              factor(baseline) categorical TRUE        
#>  7 factor(baseline)2 factor(baseline)2 factor(baseline) categorical FALSE       
#>  8 factor(baseline)3 factor(baseline)3 factor(baseline) categorical FALSE       
#>  9 factor(baseline)4 factor(baseline)4 factor(baseline) categorical FALSE       
#> 10 factor(baseline)5 factor(baseline)5 factor(baseline) categorical FALSE       
#> # … with abbreviated variable name ¹​reference_row

mod2 |> 
  tbl_regression(exponentiate = TRUE) |> 
  as_kable()
#> ℹ multgee model detected.
#> ✔ `tidy_multgee()` used instead.
#> ℹ Add `tidy_fun = broom.helpers::tidy_multgee` to quiet these messages.
```

| **Characteristic** | **exp(Beta)** | **95% CI** | **p-value** |
|:-------------------|:-------------:|:----------:|:-----------:|
| factor(time)       |               |            |             |
| 1                  |       —       |     —      |             |
| 3                  |     1.00      | 0.79, 1.27 |    \>0.9    |
| 5                  |     0.70      | 0.56, 0.87 |    0.002    |
| factor(trt)        |               |            |             |
| 1                  |       —       |     —      |             |
| 2                  |     0.60      | 0.43, 0.83 |    0.002    |
| factor(baseline)   |               |            |             |
| 1                  |       —       |     —      |             |
| 2                  |     0.51      | 0.24, 1.08 |    0.078    |
| 3                  |     0.28      | 0.14, 0.57 |   \<0.001   |
| 4                  |     0.07      | 0.03, 0.16 |   \<0.001   |
| 5                  |     0.02      | 0.01, 0.05 |   \<0.001   |

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
looks great! let me know if/when you'd like my review
