### ISSUE TITLE
Column ordering suggestion

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#19]
It would be helpful to have a standardized order the columns appear as additional information is added to the tidy tibble.  For example, all the original columns could remain on the right side of the tibble, and all new columns would be added to the left side of the tibble.

The ordering of the columns (no matter the order the functions are called) would also be standardized. The order would be selected to make it easier to digest the information in the table. For example, when the variable is added, rather than it perhaps ending up in the middle of the tibble, it would always be near the beginning.  Below is a suggested ordering:

``` r
library(broom.helpers)

lm(mpg ~ factor(cyl) + hp, mtcars) %>%
  tidy_plus_plus() %>% 
  dplyr::select(any_of(c("variable", "var_label", "var_class", "var_type", 
                         "contrasts", "reference_row", "label")), 
                everything()) %>%
  knitr::kable()
```

<table style="width:100%;">
<colgroup>
<col style="width: 7%" />
<col style="width: 7%" />
<col style="width: 6%" />
<col style="width: 7%" />
<col style="width: 10%" />
<col style="width: 8%" />
<col style="width: 3%" />
<col style="width: 8%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 7%" />
<col style="width: 6%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">factor(cyl)4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">factor(cyl)6</td>
<td style="text-align: right;">-5.9676551</td>
<td style="text-align: right;">1.6392776</td>
<td style="text-align: right;">-3.640418</td>
<td style="text-align: right;">0.0010921</td>
<td style="text-align: right;">-9.3255631</td>
<td style="text-align: right;">-2.6097471</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor(cyl)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">factor(cyl)8</td>
<td style="text-align: right;">-8.5208508</td>
<td style="text-align: right;">2.3260749</td>
<td style="text-align: right;">-3.663188</td>
<td style="text-align: right;">0.0010286</td>
<td style="text-align: right;">-13.2855993</td>
<td style="text-align: right;">-3.7561022</td>
</tr>
<tr class="even">
<td style="text-align: left;">hp</td>
<td style="text-align: left;">hp</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">hp</td>
<td style="text-align: left;">hp</td>
<td style="text-align: right;">-0.0240388</td>
<td style="text-align: right;">0.0154079</td>
<td style="text-align: right;">-1.560163</td>
<td style="text-align: right;">0.1299540</td>
<td style="text-align: right;">-0.0556005</td>
<td style="text-align: right;">0.0075228</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-08-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A simple re-ordering function could be added to the end of each `tidy_*()` function.

```r
order_tidy_columns <- function(x) {
  dplyr::select(x, 
                any_of(c("variable", "var_label", "var_class", "var_type", 
                         "contrasts", "reference_row", "label")), 
                everything())
}
```

**Comment by larmarange** [comment]
Good idea WIll implement it
