### ISSUE TITLE
Failure with dev purrr

### ISSUE THREAD

**Issue by hadley** [larmarange/broom.helpers#191]
In my revdep checks, I see:

```
Error in `rlang::check_installed(pkg = pkg, version = version, compare = compare, 
    reason = switch(!is.null(fn), stringr::str_glue("for `{fn}`")))`: `version` must be `NULL` or a vector of versions the same length as
`pkg`.
Backtrace:
    ▆
 1. ├─mod %>% tidy_and_attach() %>% ... at test-add_estimate_to_reference_rows.R:45:2
 2. └─broom.helpers::tidy_add_estimate_to_reference_rows(.)
 3.   └─broom.helpers:::.get_ref_row_estimate_contr_sum(...)
 4.     └─broom.helpers::.assert_package("emmeans", fn = "broom.helpers::tidy_add_estimate_to_reference_rows()")
 5.       └─rlang::check_installed(...)
 6.         └─rlang:::pkg_version_info(pkg, version = version, compare = compare)
 7.           └─rlang:::check_pkg_version(pkg, version, compare, call = call)
 8.             └─rlang::abort(...)
```

But I can't reproduce locally with the dev version of broom.helpers, so I suspect you've fixed it, and this is just a heads up.

**Comment by larmarange** [comment]
Hi @hadley 

Compatibility with dev version of `purrr` has been fixed in #181 

We were waiting for seeing if they were other changes required before submitting a new version of `broom.helpers` to CRAN.

Do you have an estimated date for the submission of the new version of `purrr`?

**Comment by hadley** [comment]
It's very unlikely that we'll introduce any new changes at this point, but we have not yet scheduled the release date.

**Comment by larmarange** [comment]
OK thanks for the feedback
