### ISSUE TITLE
To Think About: Check for `exponentiate=` argument in tidiers

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#197]
I've seen similar comments popping up recently, where the exponentiate argument is not respected because the underlying tidier does not have it. But it is silently being swallowed into the `...`.

https://stackoverflow.com/questions/74803815

Can we do some kind of check that we can indeed pass this arg and signal the user when it is ignored?

**Comment by larmarange** [comment]
Let's try to see if https://rlang.r-lib.org/reference/check_dots_used.html
could work in this context

Joseph Larmarange

Le mer. 14 déc. 2022 à 21:34, Daniel Sjoberg ***@***.***> a
écrit :

**Comment by ddsjoberg** [comment]
Earlier this year, broom added these types of checks (I don't think we can do it on our end). https://github.com/tidymodels/broom/pull/1104

BUT, these checks no longer seem to appear in the source code, and I can't seem to find the issue/PR where they were removed.

**Comment by larmarange** [comment]
For survreg objects, there is a warning returned by `broom::tidy()`.

However, it is not displayed by `broom.helpers` because we add a suppressWarnings.


``` r
library(survival)
library(broom.helpers)

mod <- survreg(Surv(time, status) ~ sex, dist='weibull', data=lung)

broom::tidy(mod, exponentiate = TRUE)
#> Warning: The `exponentiate` argument is not supported in the `tidy()` method for
#> `survreg` objects and will be ignored.
#> # A tibble: 3 × 5
#>   term        estimate std.error statistic   p.value
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
#> 1 (Intercept)    5.49     0.179      30.7  2.10e-206
#> 2 sex            0.396    0.128       3.10 1.94e-  3
#> 3 Log(scale)    -0.281    0.0619     -4.54 5.71e-  6
tidy_and_attach(mod, exponentiate = TRUE)
#> # A tibble: 3 × 7
#>   term        estimate std.error statistic   p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
#> 1 (Intercept)    5.49     0.179      30.7  2.10e-206    5.14      5.84 
#> 2 sex            0.396    0.128       3.10 1.94e-  3    0.145     0.646
#> 3 Log(scale)    -0.281    0.0619     -4.54 5.71e-  6   NA        NA
```

<sup>Created on 2022-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
After removing the suppressWarnings() a warning is now returned by `broom::tidy()`

``` r
library(survival)
library(broom.helpers)
library(gtsummary)
#> 
#> Attachement du package : 'gtsummary'
#> Les objets suivants sont masqués depuis 'package:broom.helpers':
#> 
#>     all_continuous, all_contrasts

mod <- survreg(Surv(time, status) ~ sex, dist='weibull', data=lung)

broom::tidy(mod, exponentiate = TRUE)
#> Warning: The `exponentiate` argument is not supported in the `tidy()` method for
#> `survreg` objects and will be ignored.
#> # A tibble: 3 × 5
#>   term        estimate std.error statistic   p.value
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
#> 1 (Intercept)    5.49     0.179      30.7  2.10e-206
#> 2 sex            0.396    0.128       3.10 1.94e-  3
#> 3 Log(scale)    -0.281    0.0619     -4.54 5.71e-  6
tidy_and_attach(mod, exponentiate = TRUE)
#> Warning: The `exponentiate` argument is not supported in the `tidy()` method for
#> `survreg` objects and will be ignored.
#> # A tibble: 3 × 7
#>   term        estimate std.error statistic   p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>
#> 1 (Intercept)    5.49     0.179      30.7  2.10e-206    5.14      5.84 
#> 2 sex            0.396    0.128       3.10 1.94e-  3    0.145     0.646
#> 3 Log(scale)    -0.281    0.0619     -4.54 5.71e-  6   NA        NA
tbl_regression(mod, exponentiate = TRUE) %>% as_kable()
#> Warning: The `exponentiate` argument is not supported in the `tidy()` method for
#> `survreg` objects and will be ignored.
```

| **Characteristic** | **exp(Beta)** | **95% CI** | **p-value** |
|:-------------------|:-------------:|:----------:|:-----------:|
| sex                |     0.40      | 0.15, 0.65 |    0.002    |

<sup>Created on 2022-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
I checked the case of a "stanreg" model.

`broom.mixed::tidy()` does not use the exponentiate argument and ignore it without warnings.

I have therefore developed a wrapper to call `tidy()` and checking that all dots are used. For the default tidier  `broom.helpers::tidy_with_broom_or_parameters()` it is taken into account.

However, be aware that `gtsummary` implements its own default behaviour in `tbl_regession()`.

Should we try to harmonize and implement some default behaviours directly in `broom.helpers`?

``` r
library(broom.helpers)
library(gtsummary)
#> 
#> Attachement du package : 'gtsummary'
#> Les objets suivants sont masqués depuis 'package:broom.helpers':
#> 
#>     all_continuous, all_contrasts
library(broom.mixed)

mod <-
  carData::Arrests |>
    rstanarm::stan_glm(
      formula = released ~ colour + year + age, family = binomial(),
      chains = 1,
      iter = 100
    )

tidy(mod, exponentiate = TRUE)
#> # A tibble: 4 × 3
#>   term         estimate std.error
#>   <chr>           <dbl>     <dbl>
#> 1 (Intercept) -137.      51.4    
#> 2 colourWhite    0.730    0.0724 
#> 3 year           0.0693   0.0256 
#> 4 age           -0.0107   0.00333
broom.helpers:::.tidy_broom(mod, exponentiate = TRUE)
#> Error in `broom.helpers:::.tidy_broom()`:
#> ! Arguments in `...` must be used.
#> ✖ Problematic argument:
#> • exponentiate = TRUE

#> Backtrace:
#>     ▆
#>  1. └─broom.helpers:::.tidy_broom(mod, exponentiate = TRUE)
#>  2.   └─rlang (local) `<fn>`()
#>  3.     └─rlang:::check_dots(env, error, action, call)
#>  4.       └─rlang:::action_dots(...)
#>  5.         ├─base (local) try_dots(...)
#>  6.         └─rlang (local) action(...)
tidy_with_broom_or_parameters(mod, exponentiate = TRUE)
#> Error in tidy_with_broom_or_parameters(mod, exponentiate = TRUE): 'exponentiate = TRUE' is not valid for this type of model.
tbl_regression(mod, exponentiate = TRUE) %>% as_kable()
```

| **Characteristic** | **OR** |  **95% CI**  |
|:-------------------|:------:|:------------:|
| colour             |        |              |
| Black              |   —    |      —       |
| White              |  0.73  |  0.62, 0.85  |
| year               |  0.07  |  0.01, 0.13  |
| age                | -0.01  | -0.02, -0.01 |

``` r
tbl_regression(mod, exponentiate = TRUE, tidy_fun = tidy_with_broom_or_parameters) %>% as_kable()
#> ! `exponentiate=TRUE` is not valid for this type of model and was ignored.
```

| **Characteristic** | **log(OR)** |  **95% CI**  |
|:-------------------|:-----------:|:------------:|
| colour             |             |              |
| Black              |      —      |      —       |
| White              |    0.73     |  0.62, 0.85  |
| year               |    0.07     |  0.01, 0.13  |
| age                |    -0.01    | -0.02, -0.01 |

<sup>Created on 2022-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
@ddsjoberg do you see other type of models we could test?

It seems that for mixed models, `tbl_regression()` is calling directly `broom.mixed::tidy()` rather than `tidy_with_broom_or_parameters()`. Would it be better to implement all customization in `broom.helpers` to have only one place to maintain?

More generally, you mentioned once the fact that it could be better to remove custom tidiers from `gtsummary`. It is possible to embed them in `broom.helpers` directly. And `tidy_with_broom_or_parameters()` could be updated to change some default behaviour. For example, it already detects `multgee` models: https://github.com/larmarange/broom.helpers/blob/main/R/tidiers.R#L45-L52

We could do the same for `gam` models: include `tidy_gam()` in `broom.helpers` and check in `tidy_with_broom_or_parameters()` if it is a gam model to redirect to `tidy_gam()`

**Comment by larmarange** [comment]
Just to be noted: checking that arguments are used reveals other bugs (example: https://github.com/tidymodels/broom/issues/1130)

I will probably have to checks if conf.int and conf.level are passed.
