### ISSUE TITLE
Fix display of p<0.001 in marginal vignette

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#205]
On this vignette https://larmarange.github.io/broom.helpers/dev/articles/marginal_tidiers.html

p-values < 0.001 are not displayed in the tables generated with `gtsummary::tbl_regression()`

It is strange because when generating the vignette on my computer, p-values below 0.001 are properly displayed. It seems that the bug appears specifically using the GitHub Action.

Dear @ddsjoberg any idea where it could be coming from?

**Comment by ddsjoberg** [comment]
Oh, that is so strange. I confirmed that the values display correctly locally for me as well.

I do recall years ago, there was an issue with `<` in gt HTML tables because the `<` was not properly escaped and it looked like an unbalanced html tag. But I haven't seen this occur in some time.

```r
library(broom.helpers)
library(gtsummary)

d <- trial %>%
  dplyr::filter(complete.cases(response, trt, marker, grade, age))

mod <- glm(
  response ~ trt * marker + stage + poly(age, 2),
  data = d,
  family = binomial
)

mod %>%
  tbl_regression(
    tidy_fun = tidy_marginalpredictions,
    newdata = "mean",
    # estimate_fun = scales::label_percent(accuracy = .1)
  ) %>%
  bold_labels()
```

**Comment by larmarange** [comment]
Closing for now
