### ISSUE TITLE
tidy_multgee not working with mice::pool

### ISSUE THREAD

**Issue by ndsubison2178** [larmarange/broom.helpers#223]
tidy_multgee not working with mice::pool does not work with mice::pool(). 

Error: No tidy method for objects of class character
In addition: Warning messages:
1: In get.dfcom(object, dfcom) : Infinite sample size assumed.
2: 'tidy.numeric' is deprecated.
See help("Deprecated")

**Comment by ddsjoberg** [comment]
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code we can run on our machines that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

**Comment by larmarange** [comment]
I'm closing for now. Please reopen the issue with a reproducible example
