### ISSUE TITLE
Add `label=` argument to `tidy_add_header_rows()`

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#23]
Is there a way to modify the header row label?  I didn't immediately see it.  If there is not, one way to solve the this is by adding an argument to `tidy_add_header_rows(label=)`.

**Comment by larmarange** [comment]
So far, the header rows label is equal to the variable label.
So, if you specify the variable label with `tidy_add_variable_labels()` before applying `tidy_add_header_rows()`, it will be taken into account.

Do you have any case where the header row label should be different from the variable label ?

**Comment by larmarange** [comment]
I have updated the example of `tidy_add_header_rows()` : https://github.com/larmarange/broom.helpers/commit/3a9eac4ce5888baa4f77ef70a44aef240bce153b

**Comment by larmarange** [comment]
https://larmarange.github.io/broom.helpers/reference/tidy_add_header_rows.html

**Comment by larmarange** [comment]
Do you think it would be enough? Or is any change required?

**Comment by ddsjoberg** [comment]
this is all great....i was accidentally using the terms label function and got confused! Sorry!

**Comment by ddsjoberg** [comment]
it's amazing that these 4 functions will replace soooooo many lines of code in gtsummary (and these are more robust). I can't wait! 🕺 

``` r
lm(mpg ~ Hmisc::rcspline.eval(hp) + factor(cyl) * am, mtcars) %>%
  tidy_and_attach() %>%
  tidy_add_variable_labels() %>%
  tidy_add_reference_rows() %>%
  tidy_add_header_rows() 
```
