### ISSUE TITLE
beta regression is not supported yet

### ISSUE THREAD

**Issue by yuryzablotski** [larmarange/broom.helpers#234]
Hi guys, beta regression can't be processed with tbl_regression(). Would be nice if it worked:

d <- mtcars %>% 
  mutate(mpg = mpg/100,
         cyl = factor(cyl))

library(betareg)
m <- betareg(mpg ~ cyl, data = d)

plot_model(m, type = "pred")

library(emmeans)
emmeans(m, pairwise ~ cyl, type = "response")

library(gtsummary)
tbl_regression(m, add_pairwise_contrasts = T)

The error message on my computer is:

Error in `dplyr::left_join()`:
! Join columns in `x` must be present in the
  data.
✖ Problem with `variable`.
Backtrace:
  1. gtsummary::tbl_regression(m, add_pairwise_contrasts = T)
 15. dplyr:::left_join.data.frame(...)

Thanks upfront! Love gtsummary!!!

**Comment by ddsjoberg** [comment]
### Things that work

`broom::tidy()`
`model.matrix()`
`model.frame()`
`terms()`  I didn't inspect the internals of the object though

### Things that need to be addressed

- The `(phi)` is being incorrectly categorized as the intercept
![image](https://github.com/larmarange/broom.helpers/assets/26774684/23bb082f-f142-430e-a2e5-098d43ca5932)
- The error is thrown when `tidy_add_reference_rows()` is run.

**Comment by larmarange** [comment]
I explored quickly beta regression. 

By the way, a nice introduction: https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide/

Beta regression have something similar with zero-inflated Poisson models, there are multi-components models, as you model both the mean and phi, each could have their own coefficients. Here, (phi) is properly interpreted as an intercept, but this is the intercept of another component.

I will therefore explore it and include betareg support in #233. Next week I'll be on leave but will explore it later after the 12 of August.

A related issue for `gtsummary` is https://github.com/ddsjoberg/gtsummary/issues/1540

Adding pairwise contrasts for such model is another question. Let's start with basic support and then see if pairwise contrast could be added or not.
