### ISSUE TITLE
Do you know the status of the {margins} pkg?

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#252]
https://cran.r-project.org/web/packages/margins/index.html

It looks like it was archived a couple of weeks ago. I haven't heard anything about plans to get it back on CRAN.

**Comment by larmarange** [comment]
I just checked. The last commit was 3 years ago: https://github.com/leeper/margins

A PR has been proposed 3 days ago to solve CRAN issue: https://github.com/leeper/margins/pull/191

Somehow, this package is now overseeded by `marginaleffects`. 

Let see if it is back on CRAN in few days/weeks. If not, I will remove the related tidier from `broom.helpers`.

**Comment by strengejacke** [comment]
_margins_ is back on CRAN. I guess it's more or less in maintainance mode and no longer under active development, similar to _broom_.

**Comment by larmarange** [comment]
Maybe we could keep tidy_margins() for now but deprecate it in favour of
marginal effects, in case margins is not maintained anymore at some point?
Joseph LARMARANGE
https://joseph.larmarange.net

Demographer PhD, Research Director at IRD
Ceped UMR 196 (Université Paris Cité - IRD)
SageSud ERL Inserm 1244
