### ISSUE TITLE
Speed improvement when _parameters_ package is used

### ISSUE THREAD

**Issue by strengejacke** [larmarange/broom.helpers#259]
I'm not sure, but looking at your code, I think you can improve the performance when you fall back to the _parameters_ package for tidying. See https://easystats.github.io/parameters/reference/model_parameters.html, documentation of `...` or section NOTE:

> For developers, if speed performance is an issue, you can use the (undocumented) `pretty_names` argument, e.g. `model_parameters(..., pretty_names = FALSE)`. This will skip the formatting of the coefficient names and make `model_parameters()` faster.

**Comment by strengejacke** [comment]
It depends on the model whether this will be important for users or not, but we had some cases where it was "immediatley" for _broom_, and "half a second" (user-perception) for _parameters_. Note that you won't get pretty labels as attribute then...

``` r
library(parameters)
mtcars$gear <- as.factor(mtcars$gear)
model <- lm(mpg ~ wt + as.factor(cyl) + gear, data = mtcars)
bench::mark(
  model_parameters(model),
  model_parameters(model, pretty_names = FALSE),
  iterations = 100,
  check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                             min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                          <bch:> <bch:>     <dbl> <bch:byt>    <dbl>
#> 1 model_parameters(model)             38.2ms 41.9ms      23.4    4.25MB     8.22
#> 2 model_parameters(model, pretty_nam… 27.4ms   30ms      31.8   177.4KB     6.98

attributes(model_parameters(model))$pretty_labels
#>     (Intercept)              wt as.factor(cyl)6 as.factor(cyl)8           gear4 
#>   "(Intercept)"            "wt"       "cyl [6]"       "cyl [8]"      "gear [4]" 
#>           gear5 
#>      "gear [5]"
attributes(model_parameters(model, pretty_names = FALSE))$pretty_labels
#>       (Intercept)                wt   as.factor(cyl)6   as.factor(cyl)8 
#>     "(Intercept)"              "wt" "as.factor(cyl)6" "as.factor(cyl)8" 
#>             gear4             gear5 
#>           "gear4"           "gear5"
```

<sup>Created on 2024-07-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
Thanks for the idea. I'm currently traveling but will look at it in the following weeks.
