### ISSUE TITLE
`tidy_multgee` Incorrectly Defines Values in `y.levels` for Nominal Logistic Regression

### ISSUE THREAD

**Issue by jackmwolf** [larmarange/broom.helpers#260]
`tidy_multgee` defines the variable `y.levels`, which, I believe, are intended to correspond to the levels of the response associated with each covariate. However, these levels are currently defined by taking factor levels (2, 3, ..., J). However, `multgee::nomLORgee` is parameterized such that factor level J is the reference group and covariates are given for the odds of levels (1, 2, ... J-1) versus the reference group (see the fitted marginal baseline category logit model in `?nomLORgee`). Therefore, `y.levels` should correspond to the *first* J-1 levels of the factor, and not the *last* J-1 levels.

**Comment by larmarange** [comment]
Thank you for having spotting it and thanks for the PR. I'm currently traveling but will look at it in the following weeks.
