### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#272]
Documentation should be improved following conventions used in `dplyr` or `gtsummary` with a clear indication of the expected class of each argument. See an example here: https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html

Should also link to *tidy-select* page or *formula-list-selector*.

**Comment by ddsjoberg** [comment]
I see you added this to tidy_plus_plus(). I like the way it looks!
