### ISSUE TITLE
R 4.2 Requirement

### ISSUE THREAD

**Issue by dannyparsons** [larmarange/broom.helpers#276]
Similar to my query here https://github.com/larmarange/ggstats/issues/72 could `broom.helpers` also change to an R 4.1 requirement which is sufficient for the new pipe (`|>`) operator? Thanks.

**Comment by larmarange** [comment]
It is more complicated here. `broom.helpers` requires `gtsummary` >= 2.0 and this version also requires R >= 2.

**Comment by larmarange** [comment]
Can't you use an older version of `broom.helpers` for the 32-bit version?

Most software (R, RStudio...) does not support anymore windows 32-bits.

**Comment by dannyparsons** [comment]
Ah, ok that's more complicated. Yes, I can use an older version instead.
