### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#32]
What is your opinion on improving the error messaging in situations like the one below: where the model is created within an `apply()` or `map()` setting and the `stats::*()` functions called on model objects fail.

``` r
library(tidyverse)
library(gtsummary)
#> #Uighur
library(survival)

# Set up map statement to create different models
tibble(grade = c("I", "II", "III")) %>%
  mutate(df_model = map(grade, ~ trial %>% filter(grade == ..1))) %>%
  mutate(
    mv_formula_char = "Surv(ttdeath, death) ~ trt + age + marker",
    mv_formula = map(mv_formula_char, ~ as.formula(.x)),
    mv_model_form =
      map2(
        mv_formula, df_model,
        ~ coxph(..1, data = ..2)
      ),
    mv_tbl_form =
      map(
        mv_model_form,
        ~ broom.helpers::tidy_plus_plus(..1, exponentiate = TRUE)
      )
  )
#> Error: Problem with `mutate()` input `mv_tbl_form`.
#> x the ... list contains fewer than 2 elements
#> i Input `mv_tbl_form` is `map(mv_model_form, ~broom.helpers::tidy_plus_plus(..1, exponentiate = TRUE))`.
```

<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In gtsummary, we added an error message like this: https://github.com/ddsjoberg/gtsummary/issues/231

**Comment by larmarange** [comment]
It has been done.

I have also changed the code to return a result in your case instead of an error (it's just that variables have not been identified).

For your information, I also tested with glm and in this case it works well.

The issue is with `model.frame()` for Cox model in that context.
