### ISSUE TITLE
tidy_add_header_rows() error with continuous * categorical interaction

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#38]
When `tidy_add_header_rows()` is run on the model below, the interaction term should be on two rows. It should have a header row with label column equal to `factor(response) * Marker Level (ng/mL)`, and a second row with label column `1 * Marker Level (ng/mL)` with the estimate.

``` r
library(gtsummary)
library(broom.helpers)
lm(age ~ factor(response) * marker, trial) %>%
  broom.helpers::tidy_and_attach() %>%
  broom.helpers::tidy_identify_variables() %>%
  broom.helpers::tidy_add_variable_labels() %>%
  broom.helpers::tidy_add_reference_rows() %>%
  broom.helpers::tidy_add_header_rows() %>%
  select(variable, var_type, var_label, label, estimate)
#> # A tibble: 6 x 5
#>   variable          var_type  var_label                 label           estimate
#>   <chr>             <chr>     <chr>                     <chr>              <dbl>
#> 1 <NA>              intercept (Intercept)               (Intercept)        44.0 
#> 2 factor(response)  categori~ factor(response)          factor(respons~    NA   
#> 3 factor(response)  categori~ factor(response)          0                  NA   
#> 4 factor(response)  categori~ factor(response)          1                   9.12
#> 5 marker            continuo~ Marker Level (ng/mL)      Marker Level (~     2.01
#> 6 factor(response)~ interact~ factor(response) * Marke~ 1 * Marker Lev~    -5.34
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
`tidy_header_rows()` add an header row only when a variable have at least two rows.
Here, the interaction variable has only one row. So no header row is added.
This is due to the fact that no reference row is added for interaction terms.

I understand your point. However, for this interaction terms, what would be the rule to decide when adding a header row? Because, if it would have been an interaction between two continuous variables, you would not add a header row.

**Comment by ddsjoberg** [comment]
I think a good rule of thumb is that we need a header row if the label doesn't make sense without it.

In the case above the label column is `"1 * Marker Level (ng/mL)"` for the interaction row.  Without the header above it to indicate the variable label (which is `"factor(response) * Marker Level (ng/mL)"`), the label column is not clear.

If we had an interaction for two continuous variables, the var label and the label column would both be `"variable1 * variable2"`, which would be clear.

**Comment by larmarange** [comment]
OK. I have updated tidy_add_header_row().  We additionally check if a term is different from its variable to identify such cases
