### ISSUE TITLE
`show_single_row=` not working for categorical-continuous interaction

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#42]
In the example below, I am requesting the interaction term `"factor(response):marker"` be printed on a single row, but it is being ignored.  

``` r
library(broom.helpers)
library(gtsummary)

lm(age ~ factor(response) * marker, trial) %>%
  tidy_and_attach() %>%
  tidy_identify_variables() %>%
  tidy_add_reference_rows() %>%
  tidy_add_variable_labels() %>%
  tidy_add_header_rows(show_single_row = "factor(response):marker") %>%
  knitr::kable()
```

<table>
<colgroup>
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 17%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 4%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 17%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: left;">header_row</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">43.985685</td>
<td style="text-align: right;">1.906507</td>
<td style="text-align: right;">23.071342</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)0</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)1</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">9.117623</td>
<td style="text-align: right;">3.536300</td>
<td style="text-align: right;">2.578294</td>
<td style="text-align: right;">0.0107814</td>
</tr>
<tr class="odd">
<td style="text-align: left;">marker</td>
<td style="text-align: left;">marker</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: right;">2.007188</td>
<td style="text-align: right;">1.609824</td>
<td style="text-align: right;">1.246836</td>
<td style="text-align: right;">0.2141828</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)1:marker</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">1 * Marker Level (ng/mL)</td>
<td style="text-align: right;">-5.337195</td>
<td style="text-align: right;">2.647510</td>
<td style="text-align: right;">-2.015930</td>
<td style="text-align: right;">0.0453914</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
tested added and fixed

**Comment by ddsjoberg** [comment]
Am I missing something?  I think this issue remains? The `"factor(response):marker"` variable is still showing on two lines.

``` r
remotes::install_github("larmarange/broom.helpers")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'broom.helpers' from a github remote, the SHA1 (013085ed) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(broom.helpers)
library(gtsummary)

lm(age ~ factor(response) * marker, trial) %>%
  tidy_and_attach() %>%
  tidy_identify_variables() %>%
  tidy_add_reference_rows() %>%
  tidy_add_variable_labels() %>%
  tidy_add_header_rows(show_single_row = "factor(response):marker") %>%
  knitr::kable()
```

<table>
<colgroup>
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 17%" />
<col style="width: 4%" />
<col style="width: 5%" />
<col style="width: 4%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 17%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
<col style="width: 4%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: left;">header_row</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">43.985685</td>
<td style="text-align: right;">1.906507</td>
<td style="text-align: right;">23.071342</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)0</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)1</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">contr.treatment</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">9.117623</td>
<td style="text-align: right;">3.536300</td>
<td style="text-align: right;">2.578294</td>
<td style="text-align: right;">0.0107814</td>
</tr>
<tr class="odd">
<td style="text-align: left;">marker</td>
<td style="text-align: left;">marker</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: right;">2.007188</td>
<td style="text-align: right;">1.609824</td>
<td style="text-align: right;">1.246836</td>
<td style="text-align: right;">0.2141828</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)1:marker</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">1 * Marker Level (ng/mL)</td>
<td style="text-align: right;">-5.337195</td>
<td style="text-align: right;">2.647510</td>
<td style="text-align: right;">-2.015930</td>
<td style="text-align: right;">0.0453914</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Oupsssss

OK I added a tests without adding reference row but I forgot a test sith reference row (because this is two different cases)!!!

Should be fixed by https://github.com/larmarange/broom.helpers/commit/5ee5781c74fecba54a38cd0ea439f48db66a8a38

**Comment by ddsjoberg** [comment]
Fantastic!  (I see that I added bad code the with the check for `bad_single_row` check..sorry! 😭 )

For the interaction handling, I think the label column should be equal to the variable label instead of the previous label that includes reference to the variable level (`"factor(response) * Marker Level (ng/mL)"` instead of `"1 * Marker Level (ng/mL)"`).

``` r
library(broom.helpers)

lm(age ~ trt + factor(response) * marker, gtsummary::trial) %>%
  tidy_and_attach() %>%
  tidy_remove_intercept() %>%
  tidy_identify_variables() %>%
  tidy_add_reference_rows() %>%
  tidy_add_variable_labels() %>%
  tidy_add_header_rows(show_single_row = c("factor(response):marker", "trt")) %>%
  dplyr::select(any_of(c("variable", "var_label", "var_type", "header_row", 
                         "reference_row", "label", "estimate"))) %>%
  knitr::kable()
```

<table>
<colgroup>
<col style="width: 17%" />
<col style="width: 29%" />
<col style="width: 8%" />
<col style="width: 8%" />
<col style="width: 10%" />
<col style="width: 18%" />
<col style="width: 8%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_label</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: left;">header_row</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">trt</td>
<td style="text-align: left;">Chemotherapy Treatment</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Chemotherapy Treatment</td>
<td style="text-align: right;">0.5592142</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">0</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">categorical</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">9.1100225</td>
</tr>
<tr class="odd">
<td style="text-align: left;">marker</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: left;">continuous</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: right;">2.0504401</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">factor(response) * Marker Level (ng/mL)</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">1 * Marker Level (ng/mL)</td>
<td style="text-align: right;">-5.3656455</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
OK code changed to also cover interaction terms

**Comment by larmarange** [comment]
Last question: do we need to flag those lines and to add a `single_row` column?
Or no need for that?

**Comment by ddsjoberg** [comment]
I don't think there is a need for that...I can't see how it would be used....... 🤔
