### ISSUE TITLE
`tidy_add_reference_rows()` erroneously adds reference row to interaction-only model

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#43]
``` r
library(broom.helpers)
library(gtsummary)
#> #BlackLivesMatter

lm(age ~ factor(response):marker, trial) %>%
  tidy_and_attach() %>%
  tidy_identify_variables() %>%
  tidy_add_reference_rows() %>%
  knitr::kable()
```

<table>
<colgroup>
<col style="width: 18%" />
<col style="width: 17%" />
<col style="width: 7%" />
<col style="width: 8%" />
<col style="width: 7%" />
<col style="width: 10%" />
<col style="width: 8%" />
<col style="width: 7%" />
<col style="width: 8%" />
<col style="width: 7%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: left;">variable</th>
<th style="text-align: left;">var_class</th>
<th style="text-align: left;">var_type</th>
<th style="text-align: left;">contrasts</th>
<th style="text-align: left;">reference_row</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">46.6357738</td>
<td style="text-align: right;">1.632164</td>
<td style="text-align: right;">28.5729753</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)0:marker</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.3957856</td>
<td style="text-align: right;">1.507993</td>
<td style="text-align: right;">0.2624585</td>
<td style="text-align: right;">0.7932857</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor(response)1:marker</td>
<td style="text-align: left;">factor(response):marker</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">interaction</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.1015807</td>
<td style="text-align: right;">1.653558</td>
<td style="text-align: right;">0.0614316</td>
<td style="text-align: right;">0.9510877</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor(response)0</td>
<td style="text-align: left;">factor(response)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
tested added and fixed

**Comment by larmarange** [comment]
Thanks for all these checks

**Comment by ddsjoberg** [comment]
WOW! So fast!

I have so many unit tests written for tbl_regression already, and I am just re-purposing them for broom.helpers! 😆  There are so many different scenarios....it took a long time to address all these edge cases.

I am so excited for the package! Thank you for your amazing work on it!

**Comment by ddsjoberg** [comment]
FYI, I finished integrating broom.helpers into gtsummary and ran all the checks.  It looks like everything is working perfectly!
https://github.com/ddsjoberg/gtsummary/pull/606

Thanks for taking the time to write the awesome package! 🥇  You've made gtsummary more robust, and simplified the internals significantly. 💯 

Once broom.helpers is on CRAN, I'll ask someone from my team to do more checking and merge the updates!  Hopefully, the first CRAN submission comes back with a small nit-picky change so the re-submission incorporates the updates from the last few days! 🕺 🕺 🕺

**Comment by larmarange** [comment]
Let's see

I just resubmitted version 1.0.0 as I didn't have feedback yet from CRAN

🤞 

Thanks for your feedback and all the new additional checks

**Comment by ddsjoberg** [comment]
It looks like it's a bit backed up with new submissions. Hopefully, there
isn't something going on with the system.

https://lockedata.github.io/cransays/articles/dashboard.html
