### ISSUE TITLE
`tidy_remove_intercept()` removes terms from model (when they are named horribly)

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#44]
This is VERY much an edge case, but wanted to let you know.  It seems that if a variable name has a `+` in it, `tidy_remove_intercept()` will remove both the intercept and the variable from the model.  If this is a complicated fix, perhaps just a message to the user, "more than one row was removed from the table. possible error occurred likely due to unusual naming conventions used for terms."

``` r
library(gtsummary)

trial2 <- 
  trial %>% 
  dplyr::mutate(`treatment +name` = trt)


glm(response ~ `treatment +name`, 
    trial2, 
    family = binomial(link = "logit")) %>%
  broom.helpers::tidy_and_attach() %>%
  broom.helpers::tidy_remove_intercept()
#> # A tibble: 0 x 8
#> # ... with 8 variables: term <chr>, variable <chr>, var_class <chr>,
#> #   var_type <chr>, estimate <dbl>, std.error <dbl>, statistic <dbl>,
#> #   p.value <dbl>
```

<sup>Created on 2020-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Thanks for having opened the issue.

The problem arrives in fact earlier when identifying variables, due to the presence in the variable name of a character with a special meaning in a regular expression.

It should have been fixed now.
