### ISSUE TITLE
Add a function model_get_coefficients_type()

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#46]
Inspired by `gtsummary:::estimate_header()`, add a function to identify model type and coefficient type.

An additional function `tidy_identify_model_type()` could add `model_type` and `coefficient_type` as attributes to the results.

It will be useful for the redesign of `GGally::ggcoef`

To @ddsjoberg , let me know if you think it could be relevant for `gtsummary` as well. I know that in `gtsummary` you also manage corresponding footnotes and translation. But I do not think that this last part is in the scope of `broom.helpers`.

**Comment by larmarange** [comment]
By the way, it could be relevant to also pass `exponentiate` as an attribute to model.

**Comment by ddsjoberg** [comment]
This could be very useful for gtsummary and it would avoid duplication of effort.  What do you have in mind?  An additional column indicating the family (e.g. Poisson, Binomial, Gaussian, etc), or something more specific?

**Comment by larmarange** [comment]
I will quickly draft something. As these two informations (model_type and coefficients_type) are global, I'm thinking about adding attributes to the tibble

**Comment by larmarange** [comment]
I just published a first draft. Still have to add tests.

`model_get_coefficients_type()` is a method, so easy to extend. It will simply return "generic", "logistic", "poisson" or "prop_hazard". Its behaviour is very similar to the first part of `gtsummary:::estimate_header()`. 
It should be easy to use within `gtsummary`.

I have added the support of multinom model and of clm/clmm ordinal models.

`tidy_add_coefficients_type()` will add the type of coefficients as an attribute called `coefficients_type` as well as a second attribute `coefficients_label` equal to "Beta", "exp(Beta)", "OR", "log(OR)", "IRR", "log(IRR)", "HR" or "log(HR)". It remains simple: no translation and no footnote.

For `gtsummary`, I feel that the easiest would be to use `model_get_coefficients_type()` and then to use your custom code as you manage also translation and footnotes.

**Comment by larmarange** [comment]
Also adding support of quasibinomial and quasipoisson

**Comment by larmarange** [comment]
and polr models

**Comment by ddsjoberg** [comment]
**Very Big Picture Question:**

I am about to submit a pull request for mice model support. I was having troubles with the model attribute being stripped and I had to update the function that re-orders the columns to also re-attach the model object.  Generally, attributes to data frames are tricky and are often dropped when we don't intend that to happen.  I am now experiencing the same problem with the `exponentiate` attribute just added.

Would it make more sense to return a list with the tidy tibble, the model object, and now the exponentiate value, rather than tacking them on as attributes?  This would also make it easier to update in the future as we wouldn't need to worry about lost attributes.

**Comment by larmarange** [comment]
That's a very good question.

My first feeling is that a list would be easier for us as developers, but less convenient for users. `tidy_*()` functions are expected to return a tibble.

An alternative would be to provide a function for saving attributes at the beginning of each `tidy_*()` and to resave them at the end (e.g. with an attributes_list argument added to `tidy_and_attach()`).

I do not understand your need to update `.order_tidy_columns()` to reattached the model. In all `tidy_` functions, the model is reattached just before applying `.order_tidy_columns()`. Do you have cases, where `.order_tidy_columns()` lose the attributes?

In that case, at the end of `tidy_*` functions, we should maybe apply `.order_tidy_columns()` before `tidy_and_attach()`

**Comment by ddsjoberg** [comment]
> My first feeling is that a list would be easier for us as developers, but less convenient for users. tidy_*() functions are expected to return a tibble.

I 100% agree with this statement! I think I was selfishly viewing the package from the point of view of a developer.

> An alternative would be to provide a function for saving attributes at the beginning of each tidy_*() and to resave them at the end (e.g. with an attributes_list argument added to tidy_and_attach()).

This is a great option. If there is a single place that would need updating

Here's the example where the ordering stripped the model attribute
``` r
library(broom.helpers)

# imputing data
imputed_trial <- mice::mice(gtsummary::trial, m = 2)
# building model
mod <- with(imputed_trial, lm(age ~ marker + grade))

# creating tidy table with model attribute
x <- mice::pool(mod) %>% mice::tidy()
attr(x, "model") <- mod$analyses[[1]]

# this is a copy of the function that orders the columns
# the model attr is stripped in the select
x %>%
  dplyr::select(
    dplyr::any_of(
      c(
        "y.level", "term", "variable", "var_label", "var_class", "var_type",
        "header_row", "contrasts", "reference_row", "label"
      )
    ),
    dplyr::everything()
  ) %>%
  attr("model")
#> NULL
```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
OK. Could have a look at https://github.com/larmarange/broom.helpers/commit/c50ad3864fcda6a16e3c2120efd52ea043f2844a and https://github.com/larmarange/broom.helpers/commit/7129ff6e01f9f0345d8142de4da94ad0a0f4073d

A new internal function `.save_attributes` is applied at the beginning of each `tidy_*` function to save selected attributes (defined only once).

At the end of each `tidy_*` function, `tidy_attach_model()` is applied. `tidy_attach_model()` is now accept a list of attributes to be attached. In addition, column sort has been moved within `tidy_attach_model()` and is performed before reattaching attributes.

Would it solve the problems you encounter?

**Comment by larmarange** [comment]
Bonus question: do you need that I transform `tidy_and_attach()` into a method, allowing to develop specific version for certain types of models?

**Comment by ddsjoberg** [comment]
I think that will solve it all, and make this kind of issue future proof!

**Comment by larmarange** [comment]
Regarding the original topic (i.e. `model_get_coefficients_type()` and `tidy_add_coefficients_type()`), do you have any additional comment? Or can I close the issue for now?

For your information, compared to current `gtsummary:::estimate_header()`, I have added the detection of quasibinomial and quasipoisson models, polr models, multinom model and ordinal clm / clmm models.

**Comment by ddsjoberg** [comment]
> Bonus question: do you need that I transform `tidy_and_attach()` into a method, allowing to develop specific version for certain types of models?

What I had done here was make a new method function `model_get_model()` that grabbed the proper model object. I thought the new function fit better in the existing framework since none of the `tidy_*()` functions are methods, and there are many methods in the `model_*()` functions.

You'll see it soon, and if you don't like the new method function, I can update

**Comment by ddsjoberg** [comment]
> Regarding the original topic (i.e. `model_get_coefficients_type()` and `tidy_add_coefficients_type()`), do you have any additional comment? Or can I close the issue for now?
> 
> For your information, compared to current `gtsummary:::estimate_header()`, I have added the detection of quasibinomial and quasipoisson models, polr models, multinom model and ordinal clm / clmm models.

I didn't look at the results yet, but it sounds fantastic!

**Comment by larmarange** [comment]
Thanks
