### ISSUE TITLE
Easier identification of dichotomous variables and all_categorical(), all_continuous(), all_dichotomous() helpers

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#54]
Dear @ddsjoberg 

I would like your opinion on the two following points.

**First**, it could be relevant to better identify dichotomous variables. An option could be to have an evolution of `var_type` created by `tidy_identify_variables()` and, for dichotomous variables, to replace the value"categorical" by "dichotomous", knowing that all dichotomous variables are also categoricals. But it could maybe have side effects in `gtsummary`.

An alternative could be to generate an additional column `dichotomous` equal to TRUE, FALSE or NA (for continuous variables).

Identifying dichotomous variables directly in `tidy_identify_variables()` would be useful later by simplifying the code of `tidy_add_header_rows()` when applying `show_single_row`.

**Second**, tidy helpers such as `all_categorical()`, `all_continuous()` and `all_dichotomous()` could be useful as well in `broom.helpers`. However, I do not know if code could be mutualised between `gtsummary()` and `broom.helpers` and if we could avoid any conflict.

As you developed these two functions and you are the one who implemented tidy selecters in `broom.helpers`, what do you think?

Best

**Comment by ddsjoberg** [comment]
I love this.  For now, these functions have only worked with `tbl_summary()`, and I have wanted to generalize them for `tbl_regression()`.  We should implement something like this!  Just need to decide on the best route!

The possible types would be continuous, categorical, dichotomous, interaction, and unknown (for when there is no `model.frame()` method)? We should probably implement selectors for all types (well, except known)? 
- `all_continuous()`
- `all_categorical(dichotomous = TRUE)`
- `all_dichotomous()`
- `all_interaction()`

I can implement the same in gtsummary, but I am not sure I'll be able to merely reexport the broom.helper functions if I want them to work with all the gtsummary obejcts.  For example, we also have a summary type called `continuous2` that has it's own selector.  There is likely a pretty straightforward way around the issue...just need to sit with it longer and think :)

**Comment by larmarange** [comment]
Sure, we should think properly how to implement it. 

If I understood properly, your trick in `broom::.tidy_tidyselect()`, you recreate a tibble (`df_empty`) with the list of variables to be able to apply `dplyr::select()`.

I guess you use something similar in `gt_summary`.

Maybe a possible trick could be to add a "var_type" attribute to each column of `df_empty`. Then, to create functions as `is_continous()`, `is_categorical()` who test the value of the attribute, and finaly to code `all_categorical()` as a `where(is_categorical)`?

Just brainstorming...

Just some clarifications: what is exactly the type `continuous2`? 

Regards

**Comment by ddsjoberg** [comment]
`continuous2` variables are those that are summarized on 2 or more rows in `tbl_summary()` and `tbl_svysummary()`.

```r
trial %>%
  select(age, trt) %>%
  tbl_summary(
    by = trt,
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_nonmiss}",
                                     "{mean} ({sd})",
                                     "{median} ({p25}, {p75})"),
    missing = "no"
  )
```
![image](https://user-images.githubusercontent.com/26774684/95539717-1cb49e00-09bd-11eb-8b19-7cf532677f7a.png)
