### ISSUE TITLE
Add broom.helpers class to tibbles?

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#56]
Should we add a broom.helpers class to the tibbles? I think this can help down the line ensuring we're working the the correct object types.
```r
class(x) <- c("broom.helpers", class(x))
```

**Comment by larmarange** [comment]
Would you just add this class or should we add additional checks in some functions?

**Comment by ddsjoberg** [comment]
What kind of checks do you have in mind?

I was thinking of it in the context of gtsummary...knowing if I am working with a broom.helpers tibble or an internal `tbl_summary()` tibble to execute the correct tidyselect-type function.

**Comment by larmarange** [comment]
Oh right !
Let's add a class then. 

To implement in tidy_and_attach then. Will do it next week
