### ISSUE TITLE
Custom tieders

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#59]
Should we add a table to the vignette with a list of compatibles models, with a note column to specify model-specific information about compatibility?

**Comment by ddsjoberg** [comment]
FYI, someone pointed out to me recently that the {easystat} family of model summaries can be put into a "broom" format.
https://twitter.com/patilindrajeets/status/1322456594068758531

I don't think broom.helpers should necessarily integrate with `model_paramters() %>% standardize_names(style = "broom")`. But it is good to know that it exists when random users report errors.

**Comment by larmarange** [comment]
Should we add a function like:

```r
parameters_tidiers <- function(model, ...) {
  if (requireNamespace("parameters"))
    stop("The 'parameters' package is required.")
  model %>% 
    parameters::model_parameters(...) %>%
    parameters::standardize_names(style = "broom")
}
```

and mention it in the documentation?

**Comment by ddsjoberg** [comment]
Hmmmm, I guess I don't think we need to export the function.  gtsummary exports a couple of custom tidiers (http://www.danieldsjoberg.com/gtsummary/dev/reference/custom_tidiers.html)....perhaps we should come up with a strategy of where these tidiers should be saved.  Maybe we do export the tidier above in broom.helpers, and the tidiers in gtsummary should also be housed in broom.helpers....or maybe we don't worry about it.  

I am fine with anything you choose.

**Comment by larmarange** [comment]
To be honest, I'm not sure this is a priority.

Somehow, it would make sense to define them in `broom.helpers`, to add a set of tests to ensure compatibility with `tidy_plus_plus` and to reexport them in `gtsummary`. On the long term, it may be appropriate.

However, it could be done at a later point.

**Comment by larmarange** [comment]
closing for now
