### ISSUE TITLE
Error when identify variables run after remove intercept

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#60]
There is a merging error when the the remove intercept function is run before the identify variables function...there are two columns for `var_nlevels`).

``` r
library(broom.helpers)

lm(age ~ marker, gtsummary::trial) %>%
  tidy_and_attach() %>%
  tidy_remove_intercept() %>%
  tidy_identify_variables() # looks like a merging error (two cols for var_nlevels)
#> # A tibble: 1 x 10
#>   term  variable var_class var_type var_nlevels.x estimate std.error statistic
#>   <chr> <chr>    <chr>     <chr>            <int>    <dbl>     <dbl>     <dbl>
#> 1 mark~ marker   numeric   continu~            NA  -0.0545      1.26   -0.0434
#> # ... with 2 more variables: p.value <dbl>, var_nlevels.y <int>
```

<sup>Created on 2020-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by larmarange** [comment]
Thanks. The bud was in tidy_identify_variables() when applied twice.

Note: it is automatically applied by tidy_remove_intercept()

Should be fixed now
