### ISSUE TITLE
Customize categorical term labels with a glue pattern

### ISSUE THREAD

**Issue by larmarange** [larmarange/broom.helpers#61]
Maybe, a feature that could be added in broom.helpers (and therefore also implemented in gtsummary) could be a function tidy_rename_categorical_terms() that would allow to do the type of renaming you want, but after model computation and at the moment the table is built. For example:

mod %>% tidy_and_attach() %>% tidy_rename_categorical_terms(pattern = "{variable} [{term}-{reference}]")
You would be able to choose whatever pattern you want.

Cf. https://github.com/ddsjoberg/gtsummary/issues/677

Note: a second argument should allow to select which variables to rename.

**Comment by larmarange** [comment]
Note: should we consider two additional tidyselectors: `all_treatment_contrasts()` and `all_sum_contrasts()`?

**Comment by larmarange** [comment]
A simpler solution:

- `tidy_add_contrasts()` all add a column `reference_term`
- `tidy_add_term_labels()` populate a column `reference_label`
- new selectors `all_treatment_coded()` and `all_sum_coded()` to select categorical variables with sum or treatment contrasts
- new function `tidy_rename_term_labels()`  with a glue label

**Comment by larmarange** [comment]
Bonus question: do we need a selector `all_intercepts()`?

**Comment by larmarange** [comment]
After thinking, I'm feeling that a better approach would be to implement a glue pattern for categorical terms through `model_list_terms_levels()` and `tidy_add_term_lables()`

Such an approach will allow to take into account the term labels when computing interaction terms.

**Comment by ddsjoberg** [comment]
> Note: should we consider two additional tidyselectors: `all_treatment_contrasts()` and `all_sum_contrasts()`?

@larmarange question for you: At the moment in the PR I am working on, I made the following contrast functions: `all_treatment_contrasts()`, `all_sum_contrasts()`, `all_poly_contrasts()`, `all_helmert_contrasts()`.

Would you prefer a single function with an argument to select the type, e.g. `all_contrasts(type = c("treatment", "sum", "poly", "helmert"))` ?

**Comment by larmarange** [comment]
one contrast function is great.

I will review the PR ASAP (not sure today, but will try tomorrow)
