### ISSUE TITLE
Unify the broom.helpers and gtsummary select helpers

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#65]
At the moment, the broom.helpers and gtsummary select helpers are created independently.  When both packages are loaded, one package will mask the others' `all_*()` selecting functions....which is not good!  I've been thinking on a way to unify the syntax, and I think I've come up with something.

Proposed changes:
1. Create a universal select function, and export it. This function will help construct each of the other helpers.  For example, if the function were called `select_constructor()`, we could define `all_continuous()` with the code below, which would select variable with type continuous.
    ```r
    all_continuous <- function() select_constructor("variable", "var_type", "continuous")
    ````
The reason for the constructor, is that I can later use it in gtsummary to easily construct selecting functions that do not apply in the broom.helpers setting. BUT, I do not need to recreate the enviornments which which we're selecting or define new scoping functions.
1. That brings us to the second point, we'd also need to export the scoping function so I can reuse it gtsummary
1. I recall a notification I received where you indicated we could add an `all_interactions()` selector and I think another one...but I can't find that message.  I'll add that here too. With the general format, it's actually very easy to add new select functions.
1. You had also mentioned at some point about adding `all_factor()`, `all_character()`, etc. functions.  I do not suggest you do this.  Since I initially released those select functions, {tidyselect} has been updated to all for selection using predicate functions, e.g. `trial %>% select(where(is.character))`.  It's in my plan to deprecate those functions so I do not need to support any supliferous functions.

The only front-facing changes here, will be exporting two new functions that help us write and use the selecting functions in other packages.  I'll start putting together a PR.

**Comment by larmarange** [comment]
Thanks @ddsjoberg for the clarifications

I agree with you and welcome a PR from you, as you are the one knowing the best this mechanism
