### ISSUE TITLE
Add a `model_get_model_frame()` method for mice objects

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#8]
The mice package does not include a `model.frame()` method for the resulting regression models from multiply imputed data sets.

Would you be ok adding one here?  I need to look up the exact code, but it'll be something like this (i can add if you're ok with it)

```r
#' @export
#' @rdname model_get_model_frame
model_get_model_frame.mipo <- function(model) {
  # add check that the mice package is installed
  
  # grab input mice data

  # extract a single dataset for our use of finding labels
   mice::complete(...)
}
```

**Comment by larmarange** [comment]
This is exactly the purpose of model_get_model_frame, adding methods for types of models who do not have the usual generics.

I do not know the `mice` package, but do not hesitate to make a PR.
