### ISSUE TITLE
Wrap `model.frame()` in `tryCatch()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [larmarange/broom.helpers#9]
Perhaps a good idea to wrap the call to `stats::model.frame(model)` in `model_get_model_frame.R` in a try catch in case the regression model does not have a method for it (like mice models).

**Comment by larmarange** [comment]
For lavaan, I have played with a dedicated method for `model_get_model_frame` that return NULL.

But should be possible to do the same with a try catch, returning NULL if an error is returned

**Comment by ddsjoberg** [comment]
Oh that is a good idea.  If there is an error, than just return NULL? You wouldn't even need a lavaan method.

**Comment by larmarange** [comment]
Exactly. If NULL is returned, then `tidy_add_variables()` will just not be able to identify the label attribute of the original variables.

**Comment by larmarange** [comment]
Note as well that model frame is also important to identify the contrasts, and therefore the reference rows.
