### ISSUE TITLE
Support crr models in tidy_plus_plus

### ISSUE THREAD

**Issue by michaelcurry1123** [larmarange/broom.helpers#91]
With the new update to `broom` it now supports `crr` models from the `cmprsk` package. However, `crr` objects do not work within `model.frame` nor `model.matrix` to extract data. Therefore `broom.helpers::tidy_plus_plus()` also throws an error when you try to pass this as an object. See example below:

library(tidyverse)
library(broom)
library(broom.helpers)
library(cmprsk)

```
set.seed(10)
ftime <- rexp(200)
fstatus <- sample(0:2,200,replace=TRUE)
cov <- matrix(runif(600),nrow=200)

mod1 <- crr(ftime,fstatus, cov)
tidy(mod1)#works 
broom.helpers::tidy_plus_plus(mod1)#doesn't work
model.frame(mod1) #error
model.matrix(mod1) #error
mod2 <- coxph(Surv(ftime,fstatus==1)~cov)#works
broom.helpers::tidy_plus_plus(mod2)#works
model.frame(mod2)#works
model.matrix(mod2)#works
```

**Comment by larmarange** [comment]
Could you try PR #89 ?

The code is more generic and should cover crr.

**Comment by michaelcurry1123** [comment]
ok great it does work for `crr`. It prints the message below but still creates the appropriate df. 
Message :
x Unable to identify the list of variables.
  
  This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
  It could be the case if that type of model does not implement these methods.
  Rarely, this error may occur if the model object was created within
  a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).

**Comment by larmarange** [comment]
> x Unable to identify the list of variables.
> 
> This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
> It could be the case if that type of model does not implement these methods.
> Rarely, this error may occur if the model object was created within
> a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).

Yes, this message is intended for such type of models, to highlight the limited support. You can deactivate it with `quiet = TRUE`
